# Site settings
title: Yuri Becker
subtitle: Blog + Site
email: yurifbeck@gmail.com
description: A place for all the my projects <br /> Hopefully this will help you and me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bolokoz.github.io" # the base hostname & protocol for your site
author: Yuri
city: Campo Grande
state: MS
#zip_code: 1337
country: Brasil
# phone: 1337 1337

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# Social settings
github_url: https://github.com/bolokoz
instagram_url: https://instagram.com/yurifbecker

# Build settings
markdown: kramdown

#My collections
permalink: pretty

collections:
  tutorials:
    output: true
