# Site settings
title: Yuri Becker
subtitle: Blog + Site
email: yurifbeck@gmail.com
description: Here is place for all my projects <br /> Hope you can learn something here today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bolokoz.github.io" # the base hostname & protocol for your site
author: Yuri
city: Campo Grande
state: MS
#zip_code: 1337
country: Brasil
# phone: 1337 1337

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# Social settings
github_url: https://github.com/bolokoz
instagram_url: https://instagram.com/yurifbecker

# Build settings
markdown: kramdown

#My collections
permalink: pretty
collections:
  tutorials:
    output: true

#Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "Yuri Becker"
